version: '3.8'

services:
  masscan-exporter:
    image: sibche/masscan_exporter
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - /opt/masscan-exporter/opt:/opt
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
